version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: fraud_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Kumar@123"
      MYSQL_DATABASE: "fraud_detection_db"
    ports:
      - "3306:3306"
    volumes:
      - mysql_production_data:/var/lib/mysql

  backend:
    image: 33065432/predictive-backend:latest
    container_name: fraud_fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db

  frontend:
    image: 33065432/predictive-frontend:latest
    container_name: store_react_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_production_data: